### ISSUE TITLE
How to know how the RAP defense worked and print out the log of the RAP defense?

### ISSUE THREAD

**Issue by oisonan1999** [erebus-attack/Bitcoin-Emulator#4]
Hello sir!
How do I know how defensively RAP is in the code and print out a log of how RAP works (I have RAP defense enabled as well as the victim being attacked by shadows IPs on day 12)
![image](https://user-images.githubusercontent.com/54930174/184580569-c17e6b50-8d1a-4d73-9c3c-d2308184d6da.png)

**Comment by akshayeshenoi** [comment]
The main logic for RAP is in the [addrman file](https://github.com/erebus-attack/Bitcoin-Emulator/blob/eb1636bfd06c4185815535f6eaed58874e98af36/src/addrman.py#L463) and is executed when the node tries to open a new connection (as detailed in Section 4.2 of our [paper](https://www.usenix.org/system/files/sec21fall-tran.pdf)). The code should help explain the logic.

Also note that if RAP is enabled, the attacker also tries to [prepare](https://github.com/erebus-attack/Bitcoin-Emulator/blob/eb1636bfd06c4185815535f6eaed58874e98af36/main.py#L27) hidden-shadow IPs to exploit the route inference errors (Section 5.1).

**Comment by oisonan1999** [comment]
Thank you for replying to me. So how do I edit the cfg.py file to see clearly that the RAP defense is actually working?

**Comment by akshayeshenoi** [comment]
If you run the emulator with `rap_enabled = False`, it will be easier for the attacker to successfully carry out the attack, i.e., occupy all outgoing connections. The attack duration will be shorter compared to when RAP was enabled.

This is the baseline scenario (Figure 3.a).

**Comment by oisonan1999** [comment]
But when I look at the log printed to the screen before and after enabling RAP, which parameter will best demonstrate that the enemy successfully attacked before turning on RAP and the enemy failed after enabling RAP?

**Comment by akshayeshenoi** [comment]
We consider the attack to succeed if the attacker has occupied all outgoing connections before the end time of the simulation. That is currently set to approximately [381 days](https://github.com/erebus-attack/Bitcoin-Emulator/blob/eb1636bfd06c4185815535f6eaed58874e98af36/cfg.py#L71) (`nStart - nEnd`, in seconds). Otherwise, the attack is said to fail.

You will have to wait for the simulation to fully complete. The only two conditions for completion are:
1. The simulation runs till `nEnd`.
2. The attacker occupies all outgoing conditions. Check [this line](https://github.com/erebus-attack/Bitcoin-Emulator/blob/eb1636bfd06c4185815535f6eaed58874e98af36/src/libemulate.py#L260).

We also log the result in the end, you should be able to clearly see the `AttackSuccess` output in your console.

**Comment by oisonan1999** [comment]
Thank you so much! It's help me a lot!!
